#!/bin/bash

# Script to help switch to i3 window manager

echo "i3 Window Manager Setup Complete!"
echo "================================="
echo ""
echo "Your i3 configuration has been installed with:"
echo "• Dual monitor support (HDMI-1 primary, HDMI-2 secondary)"
echo "• Warp Terminal assigned to workspace 1"
echo "• Brave Browser assigned to workspace 2"
echo "• Custom status bar with system information"
echo "• Window gaps, borders, and visual effects"
echo "• Various keyboard shortcuts for productivity"
echo ""
echo "To use i3:"
echo "1. Log out of your current session"
echo "2. At the login screen, select 'i3' as your session type"
echo "3. Log back in"
echo ""
echo "Key shortcuts to remember:"
echo "• Alt+Return: Open terminal"
echo "• Alt+d: Application launcher"
echo "• Alt+1-0: Switch workspaces"
echo "• Alt+Shift+q: Close window"
echo "• Alt+Shift+c: Reload i3 config"
echo ""
echo "Configuration files:"
echo "• ~/.config/i3/config (main configuration)"
echo "• ~/.config/i3status/config (status bar)"
echo "• ~/.config/i3/README.md (detailed documentation)"
echo ""
echo "Optional: Install additional packages for full functionality:"
echo "sudo pacman -S scrot thunar feh picom"
echo ""
echo "Enjoy your new i3 setup!"

